language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r aws-spring-blog *
  - mkdir -p deploy
  - mv aws-spring-blog.zip deploy/aws-spring-blog.zip

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY  # Travis repo settings에 설정된 값
  secret_access_key: $AWS_SECRET_KEY  # Travis repo settings에 설정된 값
  bucket: aws-springboot-blog-build #s3 버킷
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - "limon00029@gmail.com"